# Generated by Django 4.2 on 2024-07-22 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MesaAyuda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentes',
            name='ClosedDate',
            field=models.DateTimeField(blank=True, null=True, verbose_name='ClosedDate'),
        ),
        migrations.AlterField(
            model_name='incidentes',
            name='CreatedDate',
            field=models.DateTimeField(blank=True, null=True, verbose_name='CreatedDate'),
        ),
        migrations.AlterField(
            model_name='incidentes',
            name='ResolvedDate',
            field=models.DateTimeField(blank=True, null=True, verbose_name='ResolvedDate'),
        ),
        migrations.AlterField(
            model_name='solicitudes',
            name='ClosedDate',
            field=models.DateTimeField(blank=True, null=True, verbose_name='ClosedDate'),
        ),
        migrations.AlterField(
            model_name='solicitudes',
            name='CreatedDate1',
            field=models.DateTimeField(blank=True, null=True, verbose_name='CreatedDate'),
        ),
        migrations.AlterField(
            model_name='solicitudes',
            name='ResolvedDate1',
            field=models.DateTimeField(blank=True, null=True, verbose_name='ResolvedDate'),
        ),
    ]
