# Generated by Django 4.2 on 2024-07-22 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MesaAyuda', '0002_alter_incidentes_closeddate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solicitudes',
            old_name='AssignedUser1',
            new_name='AssignedUser',
        ),
    ]
