# Generated by Django 4.2 on 2024-07-22 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MesaAyuda', '0003_rename_assigneduser1_solicitudes_assigneduser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solicitudes',
            old_name='AffectedUser1',
            new_name='AffectedUser',
        ),
        migrations.RenameField(
            model_name='solicitudes',
            old_name='CreatedDate1',
            new_name='CreatedDate',
        ),
        migrations.RenameField(
            model_name='solicitudes',
            old_name='GrupoSoporte1',
            new_name='GrupoSoporte',
        ),
        migrations.RenameField(
            model_name='solicitudes',
            old_name='ResolvedDate1',
            new_name='ResolvedDate',
        ),
        migrations.RenameField(
            model_name='solicitudes',
            old_name='Services1',
            new_name='Services',
        ),
        migrations.RenameField(
            model_name='solicitudes',
            old_name='Status1',
            new_name='Status',
        ),
        migrations.RenameField(
            model_name='solicitudes',
            old_name='Title1',
            new_name='Title',
        ),
        migrations.RemoveField(
            model_name='solicitudes',
            name='Services2',
        ),
    ]
