# Generated by Django 4.2 on 2024-07-22 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MesaAyuda', '0004_rename_affecteduser1_solicitudes_affecteduser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudes',
            name='Servicio2',
            field=models.CharField(default='', max_length=255, verbose_name='Services2'),
        ),
    ]
